projects/quml-demo-app/src/app/quml-library-data.ts
projects/quml-library/src/lib/alert/alert.component.html
projects/quml-library/src/lib/player/player.component.html
projects/quml-library/src/lib/player/player.component.ts
projects/quml-library/src/lib/quml-library-interface.ts

Issue #SB-fix:22505: quml slider fix

---

projects/quml-library/package.json
projects/quml-library/src/lib/player/player.component.html
projects/quml-library/src/lib/player/player.component.ts
projects/quml-library/src/lib/services/viewer-service/viewer-service.ts

Issue #SB-fix 22505: quml slider fix

---

projects/quml-demo-app/src/app/question-cursor-implementation.service.ts
projects/quml-demo-app/src/app/quml-library-data.ts
projects/quml-library/src/lib/header/header.component.ts
projects/quml-library/src/lib/mcq-option/mcq-option.component.ts
projects/quml-library/src/lib/mcq-solutions/mcq-solutions.component.html
projects/quml-library/src/lib/mcq-solutions/mcq-solutions.component.ts
projects/quml-library/src/lib/mcq/mcq.component.html
projects/quml-library/src/lib/mcq/mcq.component.ts
projects/quml-library/src/lib/player/player.component.html
projects/quml-library/src/lib/player/player.component.ts
projects/quml-library/src/lib/startpage/startpage.component.html
projects/quml-library/src/lib/startpage/startpage.component.ts

<table>
<td>
</td></table>
<br />
* Software …

Issue #SB-17576 fix: fixed timer with warning time , displayed time in start page , handled replayed unselecting options

---

projects/quml-demo-app/src/app/quml-library-data.ts
projects/quml-library/src/lib/header/header.component.html
projects/quml-library/src/lib/header/header.component.ts
projects/quml-library/src/lib/player/player.component.html
projects/quml-library/src/lib/player/player.component.ts

<table>
<td>
</td></table>
<br />
* Software …

Issue #SB-17576 fix: resetting timer on replay

---

projects/quml-library/package.json
projects/quml-library/src/lib/player/player.component.ts
projects/quml-library/src/lib/services/viewer-service/viewer-service.ts

Issue #SB-22505 fix: Fixing blank list api call

---

projects/quml-library/src/lib/header/header.component.ts
projects/quml-library/src/lib/player/player.component.html
projects/quml-library/src/lib/player/player.component.ts
projects/quml-library/src/lib/sa/sa.component.html

<table>
<td>
</td></table>
<br />
* Software …

Issue #SB-17576 fix: added end event when timer expires, handled show answer button

---

projects/quml-demo-app/src/app/quml-library-data.ts
projects/quml-library/package.json
projects/quml-library/src/lib/player/player.component.html
projects/quml-library/src/lib/player/player.component.ts
projects/quml-library/src/lib/startpage/startpage.component.html
projects/quml-library/src/lib/startpage/startpage.component.ts

Issue #SB-22505 fix: Fixing quml defects

---

projects/quml-library/package.json
projects/quml-library/src/lib/player/player.component.ts
projects/quml-library/src/lib/services/viewer-service/viewer-service.ts

Issue #SB:22505 fix: Fixing quml defects

---

projects/quml-demo-app/src/app/quml-library-data.ts
projects/quml-library/package.json
projects/quml-library/src/lib/header/header.component.ts
projects/quml-library/src/lib/player/player.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24048" title="SB-24048" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24048</a>  Timer are not working on QUML player
</td></table>
<br />

Issue #SB-24048 fix: Timer are not working on QUML player

---

package.json
projects/quml-library/package.json
projects/quml-library/src/lib/player/player.component.ts
projects/quml-library/src/lib/quml-library.service.ts
projects/quml-library/src/lib/services/viewer-service/viewer-service.ts

<table>
<td>
</td></table>
<br />
* Software …

Issue #SB-17576 fix: telemetry changes

---

package-lock.json
package.json
projects/quml-library/package.json
projects/quml-library/src/lib/player/player.component.ts
projects/quml-library/src/lib/services/viewer-service/viewer-service.ts
projects/quml-library/src/lib/util-service.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24048" title="SB-24048" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24048</a>  Timer are not working on QUML player
</td></table>
<br />

Issue #SB-24048 fix: Updating to lodash-es

---

package-lock.json
projects/quml-library/package-lock.json
projects/quml-library/package.json
projects/quml-library/src/lib/player/player.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24048" title="SB-24048" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24048</a>  Timer are not working on QUML player
</td></table>
<br />

Issue #SB-24048 fix: Time spent not coming in end apge if duration ends without submit

---

projects/quml-library/package-lock.json
projects/quml-library/package.json
projects/quml-library/src/lib/header/header.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24048" title="SB-24048" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24048</a>  Timer are not working on QUML player
</td></table>
<br />

Issue #SB-24048 fix: Time spent not coming in end apge if duration ends

---

projects/quml-library/package.json
projects/quml-library/src/lib/player/player.component.ts
projects/quml-library/src/lib/quml-library.service.ts
projects/quml-library/src/lib/services/viewer-service/viewer-service.ts

<table>
<td>
</td></table>
<br />
* Software …

Issue #SB-17576 fix: Added selected values in response event

---

projects/quml-library/package.json
projects/quml-library/src/lib/alert/alert.component.html
projects/quml-library/src/lib/alert/alert.component.ts
projects/quml-library/src/lib/player/player.component.html
projects/quml-library/src/lib/player/player.component.ts
projects/quml-library/src/lib/telemetry-constants.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24085" title="SB-24085" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24085</a>  Clicking on Hints and solution  no telemetry events got found
</td></table>
<br />
* Hardware …

Issue #SB-24085 fix: added telemetry in view hints

---

projects/quml-library/package.json
projects/quml-library/src/lib/services/viewer-service/viewer-service.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24098" title="SB-24098" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24098</a>  When user is jumping from Question no 1 to 65 then UI is getting disturbed
</td></table>
<br /> …

Issue #SB-24098 fix: When user is jumping from Question no 1 to 65 then UI is getting disturbed

---

projects/quml-library/src/lib/mcq-solutions/mcq-solutions.component.html
projects/quml-library/src/lib/player/player.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-23737" title="SB-23737" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-23737</a>  Allow users to zoom-in images in Quml on both portal and mobile
</td></table>
<br />
* Hardware …

Issue #SB-23737 feat: Allow users to zoom-in solution images

---

projects/quml-library/src/lib/sa/sa.component.scss

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24233" title="SB-24233" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24233</a>  User can play the video without click on show answer in subjective question
</td></table>
<br />
…rred(fixed)
* …

Issue #SB-24233 fix: user was able to play video , when answer is blurred(fixed)

---

projects/quml-library/package.json
projects/quml-library/src/lib/icon/next/next.component.html
projects/quml-library/src/lib/icon/previous/previous.component.html

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24237" title="SB-24237" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24237</a>  Tooltip of next/previous button is incorrect
</td></table>
<br />

Issue #SB-24237 fix: Prev/next tooltip text change

---

projects/quml-library/src/lib/mcq-image-option/mcq-image-option.component.scss
projects/quml-library/src/lib/mcq-option/mcq-option.component.scss

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24038" title="SB-24038" target="_blank"><img alt="Bug" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10303&avatarType=issuetype" />SB-24038</a>  Due to some layout User is getting disturbed when Consuming in normal screen
</td></table>
<br />

Issue #SB-24038 fix: Due to some layout User is getting disturbed when Consuming in normal screen

---

projects/quml-library/package.json
projects/quml-library/src/lib/icon/next-active/next-active.component.html
projects/quml-library/src/lib/icon/previous-active/previous-active.component.html

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24237" title="SB-24237" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24237</a>  Tooltip of next/previous button is incorrect
</td></table>
<br />

Issue #SB-24237 fix: Prev/next tooltip text change - 3.8

---

projects/quml-library/src/lib/header/header.component.html
projects/quml-library/src/lib/header/header.component.scss

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24233" title="SB-24233" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24233</a>  User can play the video without click on show answer in subjective question
</td></table>
<br />
* Software …

Issue #SB-24233 fix: Making next icon disabled in scoreboard page

---

projects/quml-library/package.json
projects/quml-library/src/lib/mcq-image-option/mcq-image-option.component.html
projects/quml-library/src/lib/mcq-image-option/mcq-image-option.component.scss
projects/quml-library/src/lib/startpage/startpage.component.html
projects/quml-library/src/lib/startpage/startpage.component.scss

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24317" title="SB-24317" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24317</a>  Question set : Instructions title is not displayed as per invision in portal and app
</td></table>
<br />
* Software …

Issue #SB-24317 fix: Instructions title is not displayed

---

projects/quml-library/package.json
projects/quml-library/src/lib/startpage/startpage.component.scss

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24330" title="SB-24330" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24330</a>  Question set : Instructions : The bullets are not displayed during consumption, which was used during creation
</td></table>
<br />
…, which was used during creation in instructions
Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any …

Issue #SB-24330 fix: The bullets, tables not displayed in instructions

---

projects/quml-library/package.json

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24266" title="SB-24266" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24266</a>  Question Set : The "replay" and "exit" options are not properly aligned in the summary page
</td></table>
<br />
* …

Issue #SB-24266 fix: updated sdk version

---

projects/quml-library/package.json
projects/quml-library/src/lib/player/player.component.ts
projects/quml-library/src/lib/sa/sa.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24259" title="SB-24259" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24259</a>  Mobile App : Images are broken when the user is trying to consume a question set 
</td></table>
<br />
* Software …

Issue #Sb-24259 fix: Images are broken when the user is trying to consume a question set in mobile

---

projects/quml-library/package.json
projects/quml-library/src/lib/alert/alert.component.html
projects/quml-library/src/lib/alert/alert.component.ts
projects/quml-library/src/lib/player/player.component.html
projects/quml-library/src/lib/player/player.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24326" title="SB-24326" target="_blank"><img alt="Bug" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10303&avatarType=issuetype" />SB-24326</a>  Mobile app: Menu & Exit option is not available on end screen for pdf and epub content
</td></table>
<br />
* Software …

Issue #SB-24326 fix: Handle view hints and remove three dots at end page

---

projects/quml-library/package.json
projects/quml-library/src/lib/startpage/startpage.component.scss

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24330" title="SB-24330" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24330</a>  Question set : Instructions : The bullets are not displayed during consumption, which was used during creation
</td></table>
<br />
**Test …

Issue #SB-24330 fix: bullets were not displayed in quml instructions

---

projects/quml-library/package.json
projects/quml-library/src/lib/player/player.component.html
projects/quml-library/src/lib/player/player.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24231" title="SB-24231" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24231</a>  In images Zoom in icon is not displayed
</td></table>
<br />

Issue #SB-24231 fix: refactored zoom in and zoom out code

---

projects/quml-library/package.json
projects/quml-library/src/lib/mcq-solutions/mcq-solutions.component.scss
projects/quml-library/src/lib/player/player.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24409" title="SB-24409" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24409</a>  Solution image is not displayed completely on the Answer section.
</td></table>
<br />
* …

Issue #SB-24409 fix: full images were not displayed in solution

---

projects/quml-library/package.json
projects/quml-library/src/lib/alert/alert.component.html

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24411" title="SB-24411" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24411</a>  Nothing happens on click of hint icon available in the player.
</td></table>
<br />
* Hardware …

Issue #SB-24411 fix: hints button is removed

---

projects/quml-demo-app/src/app/quml-library-data.ts
projects/quml-library/package.json
projects/quml-library/src/lib/alert/alert.component.html
projects/quml-library/src/lib/mcq-solutions/mcq-solutions.component.scss
projects/quml-library/src/lib/player/player.component.ts
projects/quml-library/src/lib/quml-library.service.ts
projects/quml-library/src/lib/services/viewer-service/viewer-service.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-23420" title="SB-23420" target="_blank"><img alt="Bug" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10303&avatarType=issuetype" />SB-23420</a>  Course progress download errors 
</td></table>
<br />

Issue #SB-23420 fix: handled  content compatibility error and offline error

---

projects/quml-library/src/lib/player/player.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-21095" title="SB-21095" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-21095</a>  Configuration - score, feedback, solution, summary and scoring
</td></table>
<br />
* Hardware …

Issue #SB-21095 feat: Fixing content compitibility

---

projects/quml-library/src/lib/alert/alert.component.scss

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-21095" title="SB-21095" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-21095</a>  Configuration - score, feedback, solution, summary and scoring
</td></table>
<br />
* Hardware …

Issue #SB-21095 fix: alert solution design fix

---

projects/quml-library/package-lock.json
projects/quml-library/package.json

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-23430" title="SB-23430" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-23430</a>  Media/mime type compatibility on preview at creation side 
</td></table>
<br />
* Hardware …

Issue #SB-23430 fix: updated sdk version

---

projects/quml-demo-app/src/app/quml-library-data.ts
projects/quml-library/package-lock.json
projects/quml-library/package.json
projects/quml-library/src/lib/header/header.component.html
projects/quml-library/src/lib/header/header.component.ts
projects/quml-library/src/lib/player/player.component.html
projects/quml-library/src/lib/player/player.component.ts

Issue #21094 feat: Limiting no of attempts

---

projects/quml-library/package-lock.json
projects/quml-library/package.json
projects/quml-library/src/lib/header/header.component.html
projects/quml-library/src/lib/player/player.component.html
projects/quml-library/src/lib/player/player.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24783" title="SB-24783" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24783</a>  Broken image get displayed when user clicks on solution
</td></table>
<br />
* Hardware …

Issue #SB-24783 fix: Broken image fix in solutions page

---

projects/quml-library/src/lib/alert/alert.component.scss
projects/quml-library/src/lib/header/header.component.html
projects/quml-library/src/lib/header/header.component.scss
projects/quml-library/src/lib/mcq/mcq.component.scss
projects/quml-library/src/lib/player/player.component.scss

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24457" title="SB-24457" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-24457</a>  supporting various text & image formatting as enabled in creation
</td></table>
<br />

Issue #SB-24804 fix: Content Player UI refactoring with proper HTML & CSS structure

---

projects/quml-library/src/lib/player/player.component.ts
projects/quml-library/src/lib/telemetry-constants.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24788" title="SB-24788" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24788</a>  QUML: Telemetry is not getting generated when user jumps from one question to another using progress bar
</td></table>
<br />
**Test …

Issue #SB-24788 fix: Added telemetry when user click on progress bar

---

projects/quml-library/src/lib/mcq-option/mcq-option.component.ts
projects/quml-library/src/lib/mcq/mcq.component.html
projects/quml-library/src/lib/mcq/mcq.component.ts
projects/quml-library/src/lib/player/player.component.html
projects/quml-library/src/lib/player/player.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24739" title="SB-24739" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24739</a>  On click on Try gain button previous value should get erased
</td></table>
<br />
* Hardware …

Isse #SB-24739 fix: On click on Try gain button previous value should get erased

---

projects/quml-library/src/lib/header/header.component.html
projects/quml-library/src/lib/header/header.component.scss
projects/quml-library/src/lib/header/header.component.ts
projects/quml-library/src/lib/player/player.component.html
projects/quml-library/src/lib/scoreboard/scoreboard.component.scss

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24785" title="SB-24785" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24785</a>  [Mobile App]Submit button is overlapping with no. of question attempts at QUML player
</td></table>
<br />

Issue SB-24785 [Mobile App]Submit button is overlapping with no. of question attempts at QUML player

---

projects/quml-library/src/lib/player/player.component.html
projects/quml-library/src/lib/player/player.component.scss
projects/quml-library/src/lib/scoreboard/scoreboard.component.scss

End screen is not properly middle aligned from top to bottom

Issue #SB-24756 End screen is not properly middle aligned from top to bottom 

---

projects/quml-library/package-lock.json
projects/quml-library/package.json
projects/quml-library/src/lib/header/header.component.html
projects/quml-library/src/lib/header/header.component.ts
projects/quml-library/src/lib/player/player.component.html
projects/quml-library/src/lib/player/player.component.ts
projects/quml-library/src/lib/telemetry-constants.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24784" title="SB-24784" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24784</a>  [Mobile App] Answer button should not display when show solution is turned off for QUML player
</td></table>
<br /> …

Issue #SB-24784 fix: answer button will not display when show feedback is turned off

---

projects/quml-library/package-lock.json
projects/quml-library/package.json
projects/quml-library/src/lib/mcq-solutions/mcq-solutions.component.html
projects/quml-library/src/lib/player/player.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24739" title="SB-24739" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24739</a>  On click on Try again button previous value should get erased
</td></table>
<br />
* Hardware …

Issue #SB-24739 fix: Images breaking

---

package-lock.json
package.json
projects/quml-library/package.json
projects/quml-library/src/lib/player/player.component.ts
projects/quml-library/src/lib/quml-library.module.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24986" title="SB-24986" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-24986</a>  Player Migration to Angular 9
</td></table>
<br />

Issue #SB-24986 feat: Updating quml player to angular 9

---

projects/quml-library/package-lock.json
projects/quml-library/package.json
projects/quml-library/src/lib/header/header.component.ts
projects/quml-library/src/lib/player/player.component.ts

Issue #000 fix: If timer is 0, stopping timer to start

---

projects/quml-library/package-lock.json
projects/quml-library/package.json
projects/quml-library/src/lib/player/player.component.html

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25355" title="SB-25355" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-25355</a>  Left solution icon “Ans“ is missing during question set consumption
</td></table>
<br />
* …

Issue #SB-25355 fix: Showing ans icon when showsoution is true

---

projects/quml-library/package-lock.json
projects/quml-library/package.json
projects/quml-library/src/lib/alert/alert.component.html
projects/quml-library/src/lib/player/player.component.ts
projects/quml-library/src/lib/services/viewer-service/viewer-service.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25394" title="SB-25394" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-25394</a>  "Ans" icon displayed if Show Solution is true and solution is not available in Question data
</td></table>
<br />
* …

Issue #SB-25394 fix: Ans icon displayed if Show Solution is true and solution is not available in Question data

---

projects/quml-library/src/lib/player/player.component.scss
projects/quml-library/src/lib/scoreboard/scoreboard.component.scss

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25098" title="SB-25098" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-25098</a>  Text alignment in rich text and image resolution for Question set player
</td></table>
<br />

Issue#SB-25098 fix: editor class name changes for text align & image resize class removed

---

projects/quml-library/package-lock.json
projects/quml-library/package.json
projects/quml-library/src/lib/quml-library.service.ts

Issue #000 fix: cdata concat

---

projects/quml-library/package.json
projects/quml-library/src/lib/player/player.component.scss

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25097" title="SB-25097" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-25097</a>  Support for MCQ layout
</td></table>
<br />

Issue#SB-25097 fix: Support for MCQ layout

---

projects/quml-library/package-lock.json
projects/quml-library/package.json
projects/quml-library/src/lib/player/player.component.ts

Issue #25466 fix: Emiting maxattempt exceeded event

---

projects/quml-library/package-lock.json
projects/quml-library/package.json
projects/quml-library/src/lib/player/player.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25465" title="SB-25465" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-25465</a>  Best score is always coming as "0" which is incorrect
</td></table>
<br />

Issue #SB-25465 fix: Fixing score in assess event

---

projects/quml-library/package-lock.json
projects/quml-library/package.json
projects/quml-library/src/lib/player/player.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25465" title="SB-25465" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-25465</a>  Best score is always coming as "0" which is incorrect
</td></table>
<br />

Issue #SB-25465 fix: Sending params in assess events

---

projects/quml-library/package.json
projects/quml-library/src/lib/header/header.component.html
projects/quml-library/src/lib/mcq-solutions/mcq-solutions.component.scss
projects/quml-library/src/lib/player/player.component.scss

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25818" title="SB-25818" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-25818</a>  For assigned contribution org  reviewer,  the Full image is not displayed while previewing.
</td></table>
<br />

 Issue#SB-25818 fix:For assigned contribution org reviewer, the Full image is not displayed while previewing

---

projects/quml-library/package.json
projects/quml-library/src/lib/mcq-option/mcq-option.component.scss
projects/quml-library/src/lib/mcq-solutions/mcq-solutions.component.html
projects/quml-library/src/lib/mcq-solutions/mcq-solutions.component.scss
projects/quml-library/src/lib/player/player.component.scss
projects/quml-library/src/lib/sa/sa.component.html
projects/quml-library/src/lib/sa/sa.component.scss
projects/quml-library/src/lib/scoreboard/scoreboard.component.html
projects/quml-library/src/lib/scoreboard/scoreboard.component.scss

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25818" title="SB-25818" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-25818</a>  For assigned contribution org  reviewer,  the Full image is not displayed while previewing.
</td></table>
<br />

 Issue#SB-25818 fix: For assigned contribution org reviewer, the Fullimage is not displayed while previewing

---

projects/quml-library/package.json
projects/quml-library/src/lib/quml-library.service.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25582" title="SB-25582" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-25582</a>  Send all assess events to server (Mobile app)
</td></table>
<br />

Issue #SB-25582 fix: Merged release-4.0.0 to release-4.2.0

---

projects/quml-library/package.json

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25716" title="SB-25716" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-25716</a>  Accessibility guidelines
</td></table>
<br />

SB-25716 fix: accessibility fix

---

projects/quml-library/package-lock.json
projects/quml-library/package.json
projects/quml-library/src/lib/icon/zoom-in/zoom-in.component.html

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25716" title="SB-25716" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-25716</a>  Accessibility guidelines
</td></table>
<br />

Issue #SB-25716 fix: accessibility changes - player sdk

---

projects/quml-library/package.json
projects/quml-library/src/lib/header/header.component.html

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-23323" title="SB-23323" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-23323</a>  Sections within question set (single level) [Online only]
</td></table>
<br />
* Hardware …

Issue #SB-23323 fix: Fixed current Attempt count

---

README.md
projects/quml-library/README.md
projects/quml-library/package-lock.json
projects/quml-library/package.json

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-26279" title="SB-26279" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-26279</a>  Tech documentation (Content player)
</td></table>
<br />

Issue #SB-26279 feat: Quml player documentation

---

projects/quml-library/src/lib/quml-question-cursor.service.ts
projects/quml-library/src/lib/services/viewer-service/viewer-service.ts

Issue #SB-0000 feat: Send parentId along with question

---

projects/quml-library/package.json
projects/quml-library/src/lib/main-player/main-player.component.ts
projects/quml-library/src/lib/sa/sa.component.ts
projects/quml-library/src/lib/section-player/section-player.component.html
projects/quml-library/src/lib/section-player/section-player.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25599" title="SB-25599" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-25599</a>  Question set player offline playing - Mobile app
</td></table>
<br />

Issue #SB-25599 feat: Support Offline media for quml

---

README.md
projects/quml-library/README.md
projects/quml-library/src/lib/main-player/main-player.component.ts
projects/quml-library/src/lib/mcq/mcq-component.md
projects/quml-library/src/lib/quml-library-interface.ts
projects/quml-library/src/lib/quml-library.service.ts
projects/quml-library/src/lib/section-player/section-player.component.ts
projects/quml-library/src/lib/services/viewer-service/viewer-service.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-26756" title="SB-26756" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-26756</a>  Unable to see instruction while consuming Question set
</td></table>
<br />
* Hardware …

Issue #SB-26756 fix: Fixed showing instruction and added sectionId in telemetry CDATA

---

README.md
projects/quml-library/README.md
projects/quml-library/package.json
projects/quml-library/src/lib/alert/alert.component.html

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25708" title="SB-25708" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-25708</a>  Converting players into embeddable (Video, QUML)
</td></table>
<br />

Issue #SB-25708 fix: Added tech documentation for web components

---

projects/quml-library/package.json
projects/quml-library/src/lib/main-player/main-player.component.ts
projects/quml-library/src/lib/section-player/section-player.component.html

Issue #SB-43323 fix: Fixed showing maxQuestions for sections and feedback progress bar

---

projects/quml-library/package.json
projects/quml-library/src/lib/main-player/main-player.component.ts
projects/quml-library/src/lib/section-player/section-player.component.ts
projects/quml-library/src/lib/services/viewer-service/viewer-service.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-23323" title="SB-23323" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-23323</a>  Sections within question set (single level) [Online only]
</td></table>
<br />
* Hardware …

Issue #SB-23323 fix: Store question state and show replay button if maxAttempts not provided

---

projects/quml-library/package.json
projects/quml-library/src/lib/section-player/section-player.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-23323" title="SB-23323" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-23323</a>  Sections within question set (single level) [Online only] (Portal only)
</td></table>
<br />
* …

Issue #SB-23323 fix: Navigate to previous section

---

projects/quml-library/package-lock.json
projects/quml-library/package.json

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-23323" title="SB-23323" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-23323</a>  Sections within question set (single level) [Online only] (Portal only)
</td></table>
<br />
* …

Issue #SB-23323 feat: Updated player-sdk version

---

projects/quml-demo-app/src/styles.css
projects/quml-library/package-lock.json
projects/quml-library/package.json
projects/quml-library/src/lib/icon/zoom-in/zoom-in.component.html
projects/quml-library/src/lib/main-player/main-player.component.ts
projects/quml-library/src/lib/player/player.component.scss
projects/quml-library/src/lib/player/player.component.ts
projects/quml-library/src/lib/section-player/section-player.component.scss
projects/quml-library/src/lib/section-player/section-player.component.ts
projects/quml-library/src/lib/services/viewer-service/viewer-service.ts
projects/quml-library/src/lib/startpage/sb-ckeditor-styles.scss

Release 4.3.0

---

projects/quml-library/package.json
projects/quml-library/src/lib/main-player/main-player.component.ts
projects/quml-library/src/lib/quml-library-interface.ts
projects/quml-library/src/lib/section-player/section-player.component.html

Issue #SB-0000 feat: Merge release-4.4.0 to release-4.5.0

---

projects/quml-library/package.json
projects/quml-library/src/lib/main-player/main-player.component.ts
projects/quml-library/src/lib/section-player/section-player.component.scss
projects/quml-library/src/lib/section-player/section-player.component.ts
projects/quml-library/src/lib/startpage/startpage.component.scss

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-27764" title="SB-27764" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-27764</a>  User is unable to see the instruction page while there is no questions in the question set on portal and app
</td></table>
<br />
**Test …

Issue #SB-27764 fix: Fixed showing instruction page

---

projects/quml-library/ng-package.json
projects/quml-library/package-lock.json
projects/quml-library/package.json
projects/quml-library/src/lib/alert/alert.component.html
projects/quml-library/src/lib/alert/alert.component.ts
projects/quml-library/src/lib/header/header.component.html
projects/quml-library/src/lib/header/header.component.ts
projects/quml-library/src/lib/mcq-image-option/mcq-image-option.component.html
projects/quml-library/src/lib/mcq-option/mcq-option.component.ts
projects/quml-library/src/lib/mcq-solutions/mcq-solutions.component.html
projects/quml-library/src/lib/mcq-solutions/mcq-solutions.component.ts
projects/quml-library/src/lib/section-player/section-player.component.html
projects/quml-library/src/lib/section-player/section-player.component.ts

Issue #SB-0000 merge: Merged release-4.5.0 to release-4.6.0

---

README.md
projects/quml-library/README.md

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28259" title="SB-28259" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-28259</a>  inQuiry - Developer Documentation - Question Set Player
</td></table>
<br />
* Hardware …

Issue #SB-28259 feat: Add developer documentation for the player

---

README.md
projects/quml-library/README.md

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28259" title="SB-28259" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-28259</a>  inQuiry - Developer Documentation - Question Set Player
</td></table>
<br />
* Hardware …

Issue #SB-28259 fix: Updated developer documents

---

projects/quml-library/package.json
projects/quml-library/src/lib/section-player/section-player.component.ts
projects/quml-library/src/lib/startpage/startpage.component.html

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28090" title="SB-28090" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-28090</a>  Accessibility changes to Question set editor
</td></table>
<br />

Issue #SB-28090 fix: Added focus on menu button on replay button click

---

projects/quml-library/package.json
projects/quml-library/src/lib/section-player/section-player.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28090" title="SB-28090" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-28090</a>  Accessibility changes to Question set editor
</td></table>
<br />

Issue #SB-28090 fix: Added focus on the question on question-index click

---

projects/quml-library/package.json
projects/quml-library/src/lib/header/header.component.html
projects/quml-library/src/lib/header/header.component.ts
projects/quml-library/src/lib/icon/ans/ans.component.html
projects/quml-library/src/lib/sa/sa.component.html
projects/quml-library/src/lib/section-player/section-player.component.html
projects/quml-library/src/lib/section-player/section-player.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28554" title="SB-28554" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10304?size=medium" />SB-28554</a>  Ans option is not getting focused with tab and with shift tab
</td></table>
<br />
* …

Issue #SB-28554 fix: Added tabindex on Answer button

---

projects/quml-demo-app/src/app/app.component.ts
projects/quml-library/package-lock.json
projects/quml-library/package.json
projects/quml-library/src/lib/main-player/main-player.component.html
projects/quml-library/src/lib/main-player/main-player.component.ts
projects/quml-library/src/lib/quml-library-interface.ts
projects/quml-library/src/lib/services/viewer-service/viewer-service.ts
projects/quml-library/src/lib/telemetry-constants.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28633" title="SB-28633" target="_blank"><img alt="Enhancement" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10311?size=medium" />SB-28633</a>  Next content to come at end page of QUML player in a collection
</td></table>
<br />
* Software …

Issue #SB-28633 fix: Enable next content button on the endpage

---

projects/quml-library/package.json
projects/quml-library/src/lib/alert/alert.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28745" title="SB-28745" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10304?size=medium" />SB-28745</a>  Accessibility: When user clicks on next after answering a question, focus is navigated to view solution page instead of showing the feedback
</td></table>
<br />
Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details …

Issue #SB-28745 fix: Added null check

---

projects/quml-library/package.json
projects/quml-library/src/lib/main-player/main-player.component.ts
projects/quml-library/src/lib/section-player/section-player.component.ts
projects/quml-library/src/lib/services/viewer-service/viewer-service.ts
projects/quml-library/src/lib/telemetry-constants.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28719" title="SB-28719" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-28719</a>  Telemetry for skipped questions in QuML
</td></table>
<br />

Issue #SB-28719 feat: Added Assess event for viewed-skipped question

---

projects/quml-library/src/lib/section-player/section-player.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28719" title="SB-28719" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-28719</a>  Telemetry for skipped questions in QuML
</td></table>
<br />

Issue #SB-28719 feat: Raising Assess events for all questions other than Subjective questions

---

projects/quml-library/src/lib/main-player/main-player.component.html
projects/quml-library/src/lib/main-player/main-player.component.ts
projects/quml-library/src/lib/mcq-option/mcq-option.component.html
projects/quml-library/src/lib/mcq-option/mcq-option.component.ts
projects/quml-library/src/lib/quml-library-interface.ts
projects/quml-library/src/lib/section-player/section-player.component.html

Issue #SB-0000 fix: Refactored component and fixed multiple options getting selected simultaneously for options which has same text

---

.gitignore
package.json
projects/quml-library/src/lib/header/header.component.html
projects/quml-library/src/lib/header/header.component.spec.ts
projects/quml-library/src/lib/main-player/main-player.component.spec.data.ts
projects/quml-library/src/lib/main-player/main-player.component.spec.ts
projects/quml-library/src/lib/main-player/main-player.component.ts
projects/quml-library/src/lib/mcq-image-option/mcq-image-option.component.html
projects/quml-library/src/lib/mcq-image-option/mcq-image-option.component.spec.ts
projects/quml-library/src/lib/mcq-image-option/mcq-image-option.component.ts
projects/quml-library/src/lib/quml-library-interface.ts
projects/quml-library/src/lib/sa/data.ts
projects/quml-library/src/lib/section-player/section-player.component.spec.data.ts
projects/quml-library/src/lib/section-player/section-player.component.spec.ts
projects/quml-library/src/lib/section-player/section-player.component.ts
projects/quml-library/src/lib/services/viewer-service/viewer-service.data.ts
projects/quml-library/src/lib/services/viewer-service/viewer-service.spec.ts
tsconfig.json

Isssue #SB-0000 feat: Added test cases for main-component

---

projects/quml-library/package.json
projects/quml-library/src/lib/section-player/section-player.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28991" title="SB-28991" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10304?size=medium" />SB-28991</a>  Images in the question set is broken when consumed after download 
</td></table>
<br /> …

Issue #SB-28991 fix: Changed base path for downloaded content

---

projects/quml-library/src/lib/alert/alert.component.spec.ts
projects/quml-library/src/lib/alert/alert.component.ts
projects/quml-library/src/lib/header/header.component.spec.ts
projects/quml-library/src/lib/mcq-option/mcq-option.component.spec.ts
projects/quml-library/src/lib/mcq-option/mcq-option.component.ts
projects/quml-library/src/lib/mcq-question/mcq-question.component.spec.ts
projects/quml-library/src/lib/mcq-solutions/mcq-solutions.component.spec.ts
projects/quml-library/src/lib/mcq/mcq.component.spec.ts
projects/quml-library/src/lib/mcq/mcq.component.ts
projects/quml-library/src/lib/quml-library.service.data.ts
projects/quml-library/src/lib/quml-library.service.spec.ts
projects/quml-library/src/lib/quml-popup/quml-popup.component.spec.ts
projects/quml-library/src/lib/quml-popup/quml-popup.component.ts
projects/quml-library/src/lib/sa/sa.component.spec.ts
projects/quml-library/src/lib/sa/sa.component.ts
projects/quml-library/src/lib/scoreboard/scoreboard.component.spec.ts
projects/quml-library/src/lib/services/viewer-service/viewer-service.data.ts
projects/quml-library/src/lib/services/viewer-service/viewer-service.spec.ts
projects/quml-library/src/lib/startpage/startpage.component.spec.ts

Issue #SB-0000 feat: Added test cases

---

projects/quml-library/package.json
projects/quml-library/src/lib/main-player/main-player.component.ts
projects/quml-library/src/lib/section-player/section-player.component.ts

Issue #SB-27272 feat: Added auto scroll behaviour and jump to instruction page on replay

---

projects/quml-library/package.json
projects/quml-library/src/lib/header/header.component.ts
projects/quml-library/src/lib/main-player/main-player.component.ts
projects/quml-library/src/lib/section-player/section-player.component.ts
projects/quml-library/src/lib/util-service.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-27272" title="SB-27272" target="_blank"><img alt="Enhancement" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10311?size=medium" />SB-27272</a>  QUML enhancements 
</td></table>
<br />

Issue #SB-27272 feat: Updated auto scroll into view

---

projects/quml-library/package.json
projects/quml-library/src/lib/section-player/section-player.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-29143" title="SB-29143" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10304?size=medium" />SB-29143</a>  Two Assess event is getting generated for Single Question while directly jumping to the Question through Progress Bar.
</td></table>
<br />
Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test …

Issue #SB-29143 fix: Fixed generating two assess for same question

---

projects/quml-library/package.json
projects/quml-library/src/lib/mcq-option/mcq-option.component.ts
projects/quml-library/src/lib/section-player/section-player.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-29143" title="SB-29143" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10304?size=medium" />SB-29143</a>  Two Assess event is getting generated for Single Question while directly jumping to the Question through Progress Bar.
</td></table>
<br />
Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test …

Issue #SB-29143 fix: Fixed raising assess event for same option

---

projects/quml-library/package.json
projects/quml-library/src/lib/main-player/main-player.component.ts
projects/quml-library/src/lib/quml-library-interface.ts
projects/quml-library/src/lib/section-player/section-player.component.ts
projects/quml-library/src/lib/services/viewer-service/viewer-service.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-29216" title="SB-29216" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10304?size=medium" />SB-29216</a>  Offline desktop: Image is not rendering or displaying in offline mode for course within a question set or just a practice question set 
</td></table>
<br />
Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for …

Issue #SB-29216 fix: Fixed showing images offline in desktop app

---

projects/quml-library/package.json
projects/quml-library/src/lib/section-player/section-player.component.ts
projects/quml-library/src/lib/services/viewer-service/viewer-service.ts

Issue #SB-29291 fix: Fixed fetching questions

---

projects/quml-library/package.json
projects/quml-library/src/lib/mcq-image-option/mcq-image-option.component.html
projects/quml-library/src/lib/mcq-image-option/mcq-image-option.component.ts
projects/quml-library/src/lib/mcq-option/mcq-option.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-29382" title="SB-29382" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10304?size=medium" />SB-29382</a>  Feedback pop up is not displayed for "grid" and "horizontal" layouts while previewing the Question set
</td></table>
<br />
**Test …

Issue #SB-29382 fix: Fixed showing feedback popup

---

.github/workflows/code-coverage.yml
package.json
projects/quml-library/karma.conf.js
projects/quml-library/src/lib/mcq-image-option/mcq-image-option.component.spec.ts
projects/quml-library/src/lib/mcq/mcq.component.spec.ts
projects/quml-library/src/lib/section-player/section-player.component.spec.data.ts
projects/quml-library/src/lib/section-player/section-player.component.spec.ts

Issue #SB-0000 fix: Fixed test cases

---

projects/quml-library/package.json
projects/quml-library/src/lib/section-player/section-player.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-29397" title="SB-29397" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10304?size=medium" />SB-29397</a>  Mobile app: Question set consumption is not behaving as expected
</td></table>
<br />
* …

Issue #SB-29397 fix: Fixed showing scoreboard on replay

---

projects/quml-demo-app/src/app/app.component.ts
projects/quml-demo-app/src/app/quml-library-data.ts
projects/quml-library/src/lib/header/header.component.spec.ts
projects/quml-library/src/lib/main-player/main-player.component.spec.ts
projects/quml-library/src/lib/scoreboard/scoreboard.component.spec.ts
projects/quml-library/src/lib/section-player/section-player.component.spec.data.ts
projects/quml-library/src/lib/section-player/section-player.component.spec.ts
projects/quml-library/src/lib/util-service.spec.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-29184" title="SB-29184" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-29184</a>  Design changes to Submit page 
</td></table>
<br />

Issue #SB-29184 feat: Added test cases

---

projects/quml-library/package.json
projects/quml-library/src/lib/progress-indicators/progress-indicators.component.ts
projects/quml-library/src/lib/scoreboard/scoreboard.component.html

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-29184" title="SB-29184" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-29184</a>  Design changes to Submit page 
</td></table>
<br />

Issue #SB-29184 fix: Updated title for not attempted

---

projects/quml-library/package.json
projects/quml-library/src/lib/main-player/main-player.component.html
projects/quml-library/src/lib/mcq/mcq.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-29184" title="SB-29184" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-29184</a>  Design changes to Submit page 
</td></table>
<br />

Issue #SB-29184 fix: Show sidebar if enabled in config and used switch case in mcq component

---

projects/quml-library/package.json
projects/quml-library/src/lib/header/header.component.html
projects/quml-library/src/lib/header/header.component.ts
projects/quml-library/src/lib/main-player/main-player.component.html
projects/quml-library/src/lib/main-player/main-player.component.ts
projects/quml-library/src/lib/quml-library-interface.ts
projects/quml-library/src/lib/section-player/section-player.component.html
projects/quml-library/src/lib/section-player/section-player.component.spec.data.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-29642" title="SB-29642" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10304?size=medium" />SB-29642</a>  Help icon is getting displayed at the inidividual question preview level.
</td></table>
<br />
* Software …

Issue #SB-29642 feat: Added config for showing legend

---

projects/quml-library/package.json
projects/quml-library/src/lib/header/header.component.html
projects/quml-library/src/lib/main-player/main-player.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-29656" title="SB-29656" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10304?size=medium" />SB-29656</a>  Player is behaving differently when the talkback is turned off
</td></table>
<br />
…lkback is turned off
* …

Issue #SB-29656 fix: Fixed Player is behaving differently when the talkback is turned off

---

.circleci/config.yml
projects/quml-library/package.json

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25705" title="SB-25705" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-25705</a>  Automate the process of npm publish for sb-forms, common-components
</td></table>
<br /> …

Issue #SB-25705 chore: Updated circleci yml file
